/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Bookmark Searcher API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { orvalMutator } from '../utils/orval-mutator';
export interface Error {
  status_code: number;
  message: string;
}

export interface AuthToken {
  token: string;
}

export interface Bookmark {
  id: string;
  url: string;
  title?: string;
  created_at?: string;
  updated_at?: string;
}

export type Bookmarks = Bookmark[];

export type RegisterUserBody = {
  username: string;
  password: string;
};

export type LoginUserBody = {
  username: string;
  password: string;
};

export type CreateBookmarkBody = {
  url: string;
};

export type SearchBookmarksBody = {
  query: string;
};

export type SearchBookmarks200Item = {
  bookmark: Bookmark;
  similarity: number;
  chunk_content: string;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Register a new user
 */
export type registerUserResponse201 = {
  data: AuthToken
  status: 201
}

export type registerUserResponse400 = {
  data: Error
  status: 400
}

export type registerUserResponse500 = {
  data: Error
  status: 500
}
    
export type registerUserResponseSuccess = (registerUserResponse201) & {
  headers: Headers;
};
export type registerUserResponseError = (registerUserResponse400 | registerUserResponse500) & {
  headers: Headers;
};

export type registerUserResponse = (registerUserResponseSuccess | registerUserResponseError)

export const getRegisterUserUrl = () => {


  

  return `/auth/register`
}

export const registerUser = async (registerUserBody: RegisterUserBody, options?: RequestInit): Promise<registerUserResponse> => {
  
  return orvalMutator<registerUserResponse>(getRegisterUserUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      registerUserBody,)
  }
);}




export const getRegisterUserMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerUser>>, TError,{data: RegisterUserBody}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof registerUser>>, TError,{data: RegisterUserBody}, TContext> => {

const mutationKey = ['registerUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof registerUser>>, {data: RegisterUserBody}> = (props) => {
          const {data} = props ?? {};

          return  registerUser(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RegisterUserMutationResult = NonNullable<Awaited<ReturnType<typeof registerUser>>>
    export type RegisterUserMutationBody = RegisterUserBody
    export type RegisterUserMutationError = Error

    /**
 * @summary Register a new user
 */
export const useRegisterUser = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerUser>>, TError,{data: RegisterUserBody}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof registerUser>>,
        TError,
        {data: RegisterUserBody},
        TContext
      > => {
      return useMutation(getRegisterUserMutationOptions(options), queryClient);
    }
    
/**
 * @summary Login a user and receive an authentication token
 */
export type loginUserResponse200 = {
  data: AuthToken
  status: 200
}

export type loginUserResponse401 = {
  data: Error
  status: 401
}

export type loginUserResponse500 = {
  data: Error
  status: 500
}
    
export type loginUserResponseSuccess = (loginUserResponse200) & {
  headers: Headers;
};
export type loginUserResponseError = (loginUserResponse401 | loginUserResponse500) & {
  headers: Headers;
};

export type loginUserResponse = (loginUserResponseSuccess | loginUserResponseError)

export const getLoginUserUrl = () => {


  

  return `/auth/login`
}

export const loginUser = async (loginUserBody: LoginUserBody, options?: RequestInit): Promise<loginUserResponse> => {
  
  return orvalMutator<loginUserResponse>(getLoginUserUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      loginUserBody,)
  }
);}




export const getLoginUserMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginUser>>, TError,{data: LoginUserBody}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof loginUser>>, TError,{data: LoginUserBody}, TContext> => {

const mutationKey = ['loginUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loginUser>>, {data: LoginUserBody}> = (props) => {
          const {data} = props ?? {};

          return  loginUser(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type LoginUserMutationResult = NonNullable<Awaited<ReturnType<typeof loginUser>>>
    export type LoginUserMutationBody = LoginUserBody
    export type LoginUserMutationError = Error

    /**
 * @summary Login a user and receive an authentication token
 */
export const useLoginUser = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginUser>>, TError,{data: LoginUserBody}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof loginUser>>,
        TError,
        {data: LoginUserBody},
        TContext
      > => {
      return useMutation(getLoginUserMutationOptions(options), queryClient);
    }
    
/**
 * @summary Logout a user and invalidate the authentication token
 */
export type logoutUserResponse200 = {
  data: void
  status: 200
}

export type logoutUserResponse500 = {
  data: Error
  status: 500
}
    
export type logoutUserResponseSuccess = (logoutUserResponse200) & {
  headers: Headers;
};
export type logoutUserResponseError = (logoutUserResponse500) & {
  headers: Headers;
};

export type logoutUserResponse = (logoutUserResponseSuccess | logoutUserResponseError)

export const getLogoutUserUrl = () => {


  

  return `/auth/logout`
}

export const logoutUser = async ( options?: RequestInit): Promise<logoutUserResponse> => {
  
  return orvalMutator<logoutUserResponse>(getLogoutUserUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getLogoutUserMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logoutUser>>, TError,void, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof logoutUser>>, TError,void, TContext> => {

const mutationKey = ['logoutUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof logoutUser>>, void> = () => {
          

          return  logoutUser(requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type LogoutUserMutationResult = NonNullable<Awaited<ReturnType<typeof logoutUser>>>
    
    export type LogoutUserMutationError = Error

    /**
 * @summary Logout a user and invalidate the authentication token
 */
export const useLogoutUser = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logoutUser>>, TError,void, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof logoutUser>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getLogoutUserMutationOptions(options), queryClient);
    }
    
/**
 * @summary Retrieve list of bookmarks
 */
export type getBookmarksResponse200 = {
  data: Bookmarks
  status: 200
}

export type getBookmarksResponse500 = {
  data: Error
  status: 500
}
    
export type getBookmarksResponseSuccess = (getBookmarksResponse200) & {
  headers: Headers;
};
export type getBookmarksResponseError = (getBookmarksResponse500) & {
  headers: Headers;
};

export type getBookmarksResponse = (getBookmarksResponseSuccess | getBookmarksResponseError)

export const getGetBookmarksUrl = () => {


  

  return `/bookmarks`
}

export const getBookmarks = async ( options?: RequestInit): Promise<getBookmarksResponse> => {
  
  return orvalMutator<getBookmarksResponse>(getGetBookmarksUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetBookmarksQueryKey = () => {
    return [
    `/bookmarks`
    ] as const;
    }

    
export const getGetBookmarksQueryOptions = <TData = Awaited<ReturnType<typeof getBookmarks>>, TError = Error>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookmarks>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetBookmarksQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBookmarks>>> = ({ signal }) => getBookmarks({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBookmarks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetBookmarksQueryResult = NonNullable<Awaited<ReturnType<typeof getBookmarks>>>
export type GetBookmarksQueryError = Error


export function useGetBookmarks<TData = Awaited<ReturnType<typeof getBookmarks>>, TError = Error>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookmarks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBookmarks>>,
          TError,
          Awaited<ReturnType<typeof getBookmarks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBookmarks<TData = Awaited<ReturnType<typeof getBookmarks>>, TError = Error>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookmarks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBookmarks>>,
          TError,
          Awaited<ReturnType<typeof getBookmarks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBookmarks<TData = Awaited<ReturnType<typeof getBookmarks>>, TError = Error>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookmarks>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Retrieve list of bookmarks
 */

export function useGetBookmarks<TData = Awaited<ReturnType<typeof getBookmarks>>, TError = Error>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookmarks>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetBookmarksQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Create a new bookmark
 */
export type createBookmarkResponse201 = {
  data: Bookmark
  status: 201
}

export type createBookmarkResponse500 = {
  data: Error
  status: 500
}
    
export type createBookmarkResponseSuccess = (createBookmarkResponse201) & {
  headers: Headers;
};
export type createBookmarkResponseError = (createBookmarkResponse500) & {
  headers: Headers;
};

export type createBookmarkResponse = (createBookmarkResponseSuccess | createBookmarkResponseError)

export const getCreateBookmarkUrl = () => {


  

  return `/bookmarks`
}

export const createBookmark = async (createBookmarkBody: CreateBookmarkBody, options?: RequestInit): Promise<createBookmarkResponse> => {
  
  return orvalMutator<createBookmarkResponse>(getCreateBookmarkUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createBookmarkBody,)
  }
);}




export const getCreateBookmarkMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createBookmark>>, TError,{data: CreateBookmarkBody}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof createBookmark>>, TError,{data: CreateBookmarkBody}, TContext> => {

const mutationKey = ['createBookmark'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createBookmark>>, {data: CreateBookmarkBody}> = (props) => {
          const {data} = props ?? {};

          return  createBookmark(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateBookmarkMutationResult = NonNullable<Awaited<ReturnType<typeof createBookmark>>>
    export type CreateBookmarkMutationBody = CreateBookmarkBody
    export type CreateBookmarkMutationError = Error

    /**
 * @summary Create a new bookmark
 */
export const useCreateBookmark = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createBookmark>>, TError,{data: CreateBookmarkBody}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createBookmark>>,
        TError,
        {data: CreateBookmarkBody},
        TContext
      > => {
      return useMutation(getCreateBookmarkMutationOptions(options), queryClient);
    }
    
/**
 * @summary Search bookmarks by query
 */
export type searchBookmarksResponse200 = {
  data: SearchBookmarks200Item[]
  status: 200
}

export type searchBookmarksResponse500 = {
  data: Error
  status: 500
}
    
export type searchBookmarksResponseSuccess = (searchBookmarksResponse200) & {
  headers: Headers;
};
export type searchBookmarksResponseError = (searchBookmarksResponse500) & {
  headers: Headers;
};

export type searchBookmarksResponse = (searchBookmarksResponseSuccess | searchBookmarksResponseError)

export const getSearchBookmarksUrl = () => {


  

  return `/search`
}

export const searchBookmarks = async (searchBookmarksBody: SearchBookmarksBody, options?: RequestInit): Promise<searchBookmarksResponse> => {
  
  return orvalMutator<searchBookmarksResponse>(getSearchBookmarksUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      searchBookmarksBody,)
  }
);}





export const getSearchBookmarksQueryKey = (searchBookmarksBody?: SearchBookmarksBody,) => {
    return [
    `/search`, searchBookmarksBody
    ] as const;
    }

    
export const getSearchBookmarksQueryOptions = <TData = Awaited<ReturnType<typeof searchBookmarks>>, TError = Error>(searchBookmarksBody: SearchBookmarksBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchBookmarks>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchBookmarksQueryKey(searchBookmarksBody);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchBookmarks>>> = ({ signal }) => searchBookmarks(searchBookmarksBody, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchBookmarks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchBookmarksQueryResult = NonNullable<Awaited<ReturnType<typeof searchBookmarks>>>
export type SearchBookmarksQueryError = Error


export function useSearchBookmarks<TData = Awaited<ReturnType<typeof searchBookmarks>>, TError = Error>(
 searchBookmarksBody: SearchBookmarksBody, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchBookmarks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchBookmarks>>,
          TError,
          Awaited<ReturnType<typeof searchBookmarks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchBookmarks<TData = Awaited<ReturnType<typeof searchBookmarks>>, TError = Error>(
 searchBookmarksBody: SearchBookmarksBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchBookmarks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchBookmarks>>,
          TError,
          Awaited<ReturnType<typeof searchBookmarks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchBookmarks<TData = Awaited<ReturnType<typeof searchBookmarks>>, TError = Error>(
 searchBookmarksBody: SearchBookmarksBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchBookmarks>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Search bookmarks by query
 */

export function useSearchBookmarks<TData = Awaited<ReturnType<typeof searchBookmarks>>, TError = Error>(
 searchBookmarksBody: SearchBookmarksBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchBookmarks>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchBookmarksQueryOptions(searchBookmarksBody,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
