# generated by datamodel-codegen:
#   filename:  schema.yml
#   timestamp: 2026-03-03T09:53:20+00:00

from __future__ import annotations

from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, RootModel


class Error(BaseModel):
    status_code: int
    message: str


class AuthToken(BaseModel):
    token: str


class Bookmark(BaseModel):
    id: UUID
    url: AnyUrl
    title: str | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class Bookmarks(RootModel[list[Bookmark]]):
    root: list[Bookmark]
