openapi: 3.1.0
info:
  title: Bookmark Searcher API
  version: 1.0.0
paths:
  /bookmarks:
    get:
      operationId: get-bookmarks
      description: Retrieve list of bookmarks
      responses:
        '200':
          description: Successfully retrieved list of bookmarks
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bookmarks'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      operationId: create-bookmark
      description: Create a new bookmark
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - url
              properties:
                url:
                  type: string
                  format: uri
      responses:
        '201':
          description: Successfully created bookmark
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bookmark'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /search:
    post:
      operationId: search-bookmarks
      description: Search bookmarks by query
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - query
              properties:
                query:
                  type: string
      responses:
        '200':
          description: Successfully retrieved search results
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                    - bookmark
                    - similarity
                    - chunk_content
                  properties:
                    bookmark:
                      $ref: '#/components/schemas/Bookmark'
                    similarity:
                      type: number
                      format: float
                    chunk_content:
                      type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      required:
        - status_code
        - message
      properties:
        status_code:
          type: integer
        message:
          type: string
    Bookmark:
      type: object
      required:
        - id
        - url
      properties:
        id:
          type: string
          format: uuid
        url:
          type: string
          format: uri
        title:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    Bookmarks:
      type: array
      items:
        $ref: '#/components/schemas/Bookmark'
